name: Generate Apk Hash

on:
  release:
    types: [published]
    
permissions:
  contents: write
  packages: write

jobs:
  generate_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Get release asset download URL
        run: |
          ASSET_URL=$(gh release view --json assets -q '.assets[0].url')
          echo "Asset URL is $ASSET_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release asset
        run: |
          curl -L -o ./asset.apk -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $ASSET_URL

      
      - name: Calculate SHA-256 Hash
        run: |
          sha256sum ./asset.apk | awk '{print $1}' > hash.txt

      - name: Upload Hash as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hash.txt
          asset_name: hash.txt
          asset_content_type: text/plain
